# Generated by Django 4.2.14 on 2024-09-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFileImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/')),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('desc', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': '上传文件',
                'db_table': 't_upload_file',
            },
        ),
    ]
